
favicon: /assets/img/favicon.png

menu:
    home: /
    blog: /archives/
    java: /categories/java
    about: /about
    rss: /atom.xml


default:
    title: PING4GOD
    description: 三年不翅，将以长羽翼；不飞不鸣，将以观民则。
